version: "3"    

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ibarberuser
      POSTGRES_PASSWORD: ibarber2323
      POSTGRES_DB: ibarberdb
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ibarberuser -d ibarberdb -h db"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: 
      context: .
    ports:
      - 3000:3000
    depends_on:
      db: 
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://ibarberuser:ibarber2323@db:5432/ibarberdb
    volumes:
      - .:/app
volumes:
  dbdata: