version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ibarberdb
      POSTGRES_PASSWORD: ibarberdb
      POSTGRES_DB: ibarberdb
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data