version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ibarberuser
      POSTGRES_PASSWORD: ibarber2323
      POSTGRES_DB: ibarberdb
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://ibarberuser:ibarber2323@db:5432/ibarberdb
volumes:
  dbdata: